### ISSUE TITLE
Live sample

### ISSUE THREAD

**Issue by artlantis** [marcog83/RoboJS#3]
it would be nice to see a live example of custom elements/webcomponents with RoboJS. I understand the technique well but don't know how can we use in real life.

**Comment by marcog83** [comment]
Hi, as soon as possible I will write a live example, thanks for the advice

**Comment by marcog83** [comment]
Hi,
I created a quick demo on [http://marcog83.github.io/RoboJS/](http://marcog83.github.io/RoboJS/)
It simulate a bunch of modules loaded from server (on the left), and a page where to place them (on the right). 
Hope it can be useful.

**Comment by artlantis** [comment]
Oh, wonderful. Thank you so much.
